name: Scanner L&K Automatico

on:
  schedule:
    - cron: '0 */2 * * *' # Si avvia ogni 2 ore esatte (00:00, 02:00, 04:00, ecc.)
  workflow_dispatch:      # Ti permette sempre di avviarlo a mano se serve

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Accedi al repository
        uses: actions/checkout@v3

      - name: Configura PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Esegui lo script di scansione
        run: php scanner.php

      - name: Salva i risultati nel repository
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add mondo327.json
          git commit -m "Update database castelli $(date)" || exit 0
          git push
